### ISSUE TITLE
Use pouchdb-promise

### ISSUE THREAD

**Issue by jo** [pouchdb/plugin-seed#9]
https://github.com/calvinmetcalf/pouchdb-promise

**Comment by nolanlawson** [comment]
pouchdb-promise is on the way out. soon it will be `require('pouchdb/extras/promise')`. see https://github.com/pouchdb/pouchdb/pull/3730

**Comment by jo** [comment]
That sounds promising!
Am 13.04.2015 18:25 schrieb Nolan Lawson <notifications@github.com>:pouchdb-promise is on the way out. soon it will be require('pouchdb/extras/promise'). see pouchdb/pouchdb#3730

**Comment by nolanlawson** [comment]
:laughing:
